global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # RabbitMQ metrics via exporter
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 15s
    metrics_path: /metrics

  # LLM metrics service
  - job_name: 'llm-metrics'
    static_configs:
      - targets: ['llm-metrics-service:8080']
    scrape_interval: 30s
    metrics_path: /metrics
