apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: metrics
    user: prometheus
    secureJsonData:
      password: prometheus_password
    jsonData:
      sslmode: disable
      timescaledb: true
    editable: true
